import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Współdzielnia mieszkaniowa",
  description: "Generated by create next app",
};
//ten layout jest na kazdej podstronie
//dodawac "use client"; gdy robimy jakis react component generowany po stronie klienta
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
        {children} 
      </body>
    </html>
  );
}
